# Site settings
baseurl = "http://chung.loan" #without ending slash
languageCode = "en-us"
title = "Chung's Profile"
theme = "hugo-identity-theme"
#themesDir = "../.."

# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-XXXXX-Y"

[params]
  
  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance
  
  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  #custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Chung Nguyen"
    # Avatars can be written to images/avatars/
    avatar = "chung.jpg"
    position = "Software Engineer"
    livesIn = "[Brisbane, Australia](https://en.wikipedia.org/wiki/Brisbane)"
    scope = [
        "[Github projects](https://github.com/chung)",
        "[LinkedIn profile](https://www.linkedin.com/in/chunglun/)"
      ]
    biography = """Chung is an old school software engineer.
    He read [The Practice of Programming](https://en.wikipedia.org/wiki/The_Practice_of_Programming) cover to cover when it first come out. Graduated from [UNSW](https://www.unsw.edu.au), he has lived in Sydney, Atlanta and Saigon.
    He now enjoys the [beautiful river city](https://en.wikipedia.org/wiki/Brisbane). He likes outdoor and nature. Hiking and fishing are his favourite pastimes. He also loves playing chess and once wrote a chess server just so he could play with his long-distance friends.
    He believes life is truly an amazing adventure. So he is not afraid to try and experiment, especially learning new things.
    Recently he even taught himself how to [play the piano](http://learn-piano.herokuapp.com/basics/).
    """



  # Contact form settings
    
  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "nguyenhongchung@gmail.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = false
    title = "Touch Me!"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send it"
    success = "Thank you for contacting us."
    error = "Message could not be send. Please contact us at vinasearch1@gmail.com"

    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others
  #[[params.social]]
  #  title = "Twitter"
  #  icon = "fa-twitter"
  #  link = "#"

  #[[params.social]]
  #  title = "Instagram"
  #  icon = "fa-instagram"
  #  link = "#"
    
  #[[params.social]]
  #  title = "Facebook"
  #  icon = "fa-facebook"
  #  link = "#"


  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "2017"

  # Page license
  #[params.license]
  #  link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
  #  name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="
